import { Component, ViewChild, AfterViewInit} from '@angular/core';
import { AppConfig } from '../_services/app.config';
import { JsonEditorComponent, JsonEditorOptions } from 'ang-jsoneditor';
import { IAppConfig } from '../_models/app-config.model';

@Component({
  selector: 'app-editor',
  templateUrl: './editor.component.html',
  styleUrls: ['./editor.component.css']
})
export class EditorComponent implements AfterViewInit{


  /** Generated by https://jsonschema.net/ <br>
  *  General schema for configuration file.
  */
  schema =    {
     "definitions": {},
     "$schema": "http://json-schema.org/draft-07/schema#",
     "$id": "http://example.com/root.json",
     "type": "object",
     "title": "The Root Schema",
     "required": [
       "charts",
       "supplies",
      "devices",
      "general",
      "deployment"
    ],
    "properties": {
      "charts": {
        "$id": "#/properties/charts",
        "type": "array",
        "title": "The Charts Schema",
        "items": {
          "$id": "#/properties/charts/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "col",
            "chartId",
            "axes",
            "datasets",
            "maxValues",
            "name"
          ],
          "properties": {
            "col": {
              "$id": "#/properties/charts/items/properties/col",
              "type": "object",
              "title": "The Col Schema",
              "required": [
                "xs",
                "md",
                "sm",
                "lg"
              ],
              "properties": {
                "xs": {
                  "$id": "#/properties/charts/items/properties/col/properties/xs",
                  "type": "integer",
                  "title": "The Xs Schema",
                  "default": 0,
                  "examples": [
                    12
                  ]
                },
                "md": {
                  "$id": "#/properties/charts/items/properties/col/properties/md",
                  "type": "integer",
                  "title": "The Md Schema",
                  "default": 0,
                  "examples": [
                    12
                  ]
                },
                "sm": {
                  "$id": "#/properties/charts/items/properties/col/properties/sm",
                  "type": "integer",
                  "title": "The Sm Schema",
                  "default": 0,
                  "examples": [
                    12
                  ]
                },
                "lg": {
                  "$id": "#/properties/charts/items/properties/col/properties/lg",
                  "type": "integer",
                  "title": "The Lg Schema",
                  "default": 0,
                  "examples": [
                    6
                  ]
                }
              }
            },
            "chartId": {
              "$id": "#/properties/charts/items/properties/chartId",
              "type": "string",
              "title": "The Chartid Schema",
              "default": "",
              "examples": [
                "Chart#1"
              ],
              "pattern": "^(.*)$"
            },
            "axes": {
              "$id": "#/properties/charts/items/properties/axes",
              "type": "array",
              "title": "The Axes Schema",
              "items": {
                "$id": "#/properties/charts/items/properties/axes/items",
                "type": "object",
                "title": "The Items Schema",
                "required": [
                 "id",
                 "position"
               ],
               "properties": {
                 "id": {
                   "$id": "#/properties/charts/items/properties/axes/items/properties/id",
                   "type": "string",
                   "title": "The Id Schema",
                   "default": "",
                   "examples": [
                     "yAxis1"
                   ],
                   "pattern": "^(.*)$"
                 },
                 "position": {
                   "$id": "#/properties/charts/items/properties/axes/items/properties/position",
                   "type": "string",
                   "title": "The Position Schema",
                   "default": "",
                   "examples": [
                     "left"
                   ],
                   "pattern": "^(.*)$"
                 }
               }
             }
           },
           "datasets": {
             "$id": "#/properties/charts/items/properties/datasets",
             "type": "array",
             "title": "The Datasets Schema",
             "items": {
               "$id": "#/properties/charts/items/properties/datasets/items",
               "type": "object",
               "title": "The Items Schema",
               "required": [
                 "handler",
                 "autoLabel",
                 "sourceId",
                 "datasetId",
                 "borderColor",
                 "customDataHandlerEnabled",
                 "negRange",
                 "autoRange",
                 "name",
                 "chartDataset",
                 "unit"
               ],
               "properties": {
                 "handler": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/handler",
                   "type": "string",
                   "title": "The Handler Schema",
                   "default": "",
                   "examples": [
                     ""
                   ],
                   "pattern": "^(.*)$"
                 },
                 "autoLabel": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/autoLabel",
                   "type": "boolean",
                   "title": "The Autolabel Schema",
                   "default": false,
                   "examples": [
                     true
                   ]
                 },
                 "sourceId": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/sourceId",
                   "type": "string",
                   "title": "The Sourceid Schema",
                   "default": "",
                   "examples": [
                     "vm1"
                   ],
                   "pattern": "^(.*)$"
                 },
                 "datasetId": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/datasetId",
                   "type": "string",
                   "title": "The Datasetid Schema",
                   "default": "",
                   "examples": [
                     "ADS1dataset"
                   ],
                   "pattern": "^(.*)$"
                 },
                 "borderColor": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/borderColor",
                   "type": "string",
                   "title": "The Bordercolor Schema",
                   "default": "",
                   "examples": [
                     "#2196f3"
                   ],
                   "pattern": "^(.*)$"
                 },
                 "customDataHandlerEnabled": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/customDataHandlerEnabled",
                   "type": "boolean",
                   "title": "The Customdatahandlerenabled Schema",
                   "default": false,
                   "examples": [
                     false
                   ]
                 },
                 "negRange": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/negRange",
                   "type": "boolean",
                   "title": "The Negrange Schema",
                   "default": false,
                   "examples": [
                     false
                   ]
                 },
                 "autoRange": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/autoRange",
                   "type": "boolean",
                   "title": "The Autorange Schema",
                   "default": false,
                   "examples": [
                     true
                   ]
                 },
                 "name": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/name",
                   "type": "string",
                   "title": "The Name Schema",
                   "default": "",
                   "examples": [
                     "Voltage vm1"
                   ],
                   "pattern": "^(.*)$"
                 },
                 "chartDataset": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/chartDataset",
                   "type": "object",
                   "title": "The Chartdataset Schema",
                   "required": [
                     "yAxisID",
                     "fill",
                     "label",
                     "currValue",
                     "borderColor"
                   ],
                   "properties": {
                     "yAxisID": {
                       "$id": "#/properties/charts/items/properties/datasets/items/properties/chartDataset/properties/yAxisID",
                       "type": "string",
                       "title": "The Yaxisid Schema",
                       "default": "",
                       "examples": [
                         "yAxis1"
                       ],
                       "pattern": "^(.*)$"
                     },
                     "fill": {
                       "$id": "#/properties/charts/items/properties/datasets/items/properties/chartDataset/properties/fill",
                       "type": "boolean",
                       "title": "The Fill Schema",
                       "default": false,
                       "examples": [
                         false
                       ]
                     },
                     "label": {
                       "$id": "#/properties/charts/items/properties/datasets/items/properties/chartDataset/properties/label",
                       "type": "string",
                       "title": "The Label Schema",
                       "default": "",
                       "examples": [
                         "Voltage vm1[mV]"
                       ],
                       "pattern": "^(.*)$"
                     },
                     "currValue": {
                       "$id": "#/properties/charts/items/properties/datasets/items/properties/chartDataset/properties/currValue",
                       "type": "number",
                       "title": "The Currvalue Schema",
                       "default": 0.0,
                       "examples": [
                         24.536
                       ]
                     },
                     "borderColor": {
                       "$id": "#/properties/charts/items/properties/datasets/items/properties/chartDataset/properties/borderColor",
                       "type": "string",
                       "title": "The Bordercolor Schema",
                       "default": "",
                       "examples": [
                         "#0618f9"
                       ],
                       "pattern": "^(.*)$"
                     }
                   }
                 },
                 "unit": {
                   "$id": "#/properties/charts/items/properties/datasets/items/properties/unit",
                   "type": "string",
                   "title": "The Unit Schema",
                   "default": "",
                   "examples": [
                     "mV"
                   ],
                   "pattern": "^(.*)$"
                 }
               }
             }
           },
           "maxValues": {
             "$id": "#/properties/charts/items/properties/maxValues",
             "type": "integer",
             "title": "The Maxvalues Schema",
             "default": 0,
             "examples": [
               40
             ]
           },
           "name": {
             "$id": "#/properties/charts/items/properties/name",
             "type": "string",
             "title": "The Name Schema",
             "default": "",
             "examples": [
               "Voltage chart"
             ],
             "pattern": "^(.*)$"
           }
         }
       }
     },
     "supplies": {
       "$id": "#/properties/supplies",
       "type": "array",
       "title": "The Supplies Schema",
       "items": {
         "$id": "#/properties/supplies/items",
         "type": "object",
         "title": "The Items Schema",
         "required": [
           "enabled",
           "type",
           "currentVoltage",
           "maxValue",
           "minValue",
           "id",
           "stepSize",
           "unit",
           "name"
         ],
         "properties": {
           "enabled": {
             "$id": "#/properties/supplies/items/properties/enabled",
             "type": "boolean",
             "title": "The Enabled Schema",
             "default": false,
             "examples": [
               true
             ]
           },
           "type": {
             "$id": "#/properties/supplies/items/properties/type",
             "type": "string",
             "title": "The Type Schema",
             "default": "",
             "examples": [
               "BodyBias"
             ],
             "pattern": "^(.*)$"
           },
           "currentVoltage": {
             "$id": "#/properties/supplies/items/properties/currentVoltage",
             "type": "integer",
             "title": "The Currentvoltage Schema",
             "default": 0,
             "examples": [
               2
             ]
           },
           "maxValue": {
             "$id": "#/properties/supplies/items/properties/maxValue",
             "type": "number",
             "title": "The Maxvalue Schema",
             "default": 0.0,
             "examples": [
               2.5
             ]
           },
           "minValue": {
             "$id": "#/properties/supplies/items/properties/minValue",
             "type": "integer",
             "title": "The Minvalue Schema",
             "default": 0,
             "examples": [
               0
             ]
           },
           "id": {
             "$id": "#/properties/supplies/items/properties/id",
             "type": "string",
             "title": "The Id Schema",
             "default": "",
             "examples": [
               "BBP"
             ],
             "pattern": "^(.*)$"
           },
           "stepSize": {
             "$id": "#/properties/supplies/items/properties/stepSize",
             "type": "number",
             "title": "The Stepsize Schema",
             "default": 0.0,
             "examples": [
               0.005
             ]
           },
           "unit": {
             "$id": "#/properties/supplies/items/properties/unit",
             "type": "string",
             "title": "The Unit Schema",
             "default": "",
             "examples": [
               "V"
             ],
             "pattern": "^(.*)$"
           },
           "name": {
             "$id": "#/properties/supplies/items/properties/name",
             "type": "string",
             "title": "The Name Schema",
             "default": "",
             "examples": [
               "BodyBiasingPos"
             ],
             "pattern": "^(.*)$"
           }
         }
       }
     },
     "devices": {
       "$id": "#/properties/devices",
       "type": "array",
       "title": "The Devices Schema",
       "items": {
         "$id": "#/properties/devices/items",
         "type": "object",
         "title": "The Items Schema",
         "required": [
           "autoResolution",
           "type",
           "currentResolution",
           "deviceId",
           "name"
         ],
         "properties": {
           "autoResolution": {
             "$id": "#/properties/devices/items/properties/autoResolution",
             "type": "boolean",
             "title": "The Autoresolution Schema",
             "default": false,
             "examples": [
               true
             ]
           },
           "type": {
             "$id": "#/properties/devices/items/properties/type",
             "type": "string",
             "title": "The Type Schema",
             "default": "",
             "examples": [
               "voltage"
             ],
             "pattern": "^(.*)$"
           },
           "currentResolution": {
             "$id": "#/properties/devices/items/properties/currentResolution",
             "type": "integer",
             "title": "The Currentresolution Schema",
             "default": 0,
             "examples": [
               3
             ]
           },
           "deviceId": {
             "$id": "#/properties/devices/items/properties/deviceId",
             "type": "string",
             "title": "The Deviceid Schema",
             "default": "",
             "examples": [
               "vm1"
             ],
             "pattern": "^(.*)$"
           },
           "name": {
             "$id": "#/properties/devices/items/properties/name",
             "type": "string",
             "title": "The Name Schema",
             "default": "",
             "examples": [
               "ADS1"
             ],
             "pattern": "^(.*)$"
           }
         }
       }
     },
     "general": {
       "$id": "#/properties/general",
       "type": "object",
       "title": "The General Schema",
       "required": [
         "currentResolutionMap",
         "voltageResolutionMap",
         "maxDataPoints",
         "chartOptions",
         "timerInterval"
       ],
       "properties": {
         "currentResolutionMap": {
           "$id": "#/properties/general/properties/currentResolutionMap",
           "type": "array",
           "title": "The Currentresolutionmap Schema",
           "items": {
             "$id": "#/properties/general/properties/currentResolutionMap/items",
             "type": "string",
             "title": "The Items Schema",
             "default": "",
             "examples": [
               "500uA",
               "50mA"
             ],
             "pattern": "^(.*)$"
           }
         },
         "voltageResolutionMap": {
           "$id": "#/properties/general/properties/voltageResolutionMap",
           "type": "array",
           "title": "The Voltageresolutionmap Schema",
           "items": {
             "$id": "#/properties/general/properties/voltageResolutionMap/items",
             "type": "string",
             "title": "The Items Schema",
             "default": "",
             "examples": [
               "50mV",
               "500mV",
               "5V"
             ],
             "pattern": "^(.*)$"
           }
         },
         "maxDataPoints": {
           "$id": "#/properties/general/properties/maxDataPoints",
           "type": "integer",
           "title": "The Maxdatapoints Schema",
           "default": 0,
           "examples": [
             50
           ]
         },
         "chartOptions": {
           "$id": "#/properties/general/properties/chartOptions",
           "type": "object",
           "title": "The Chartoptions Schema",
           "required": [
             "animation",
             "responsive",
             "legend",
             "scales"
           ],
           "properties": {
             "animation": {
               "$id": "#/properties/general/properties/chartOptions/properties/animation",
               "type": "object",
               "title": "The Animation Schema",
               "required": [
                 "duration"
               ],
               "properties": {
                 "duration": {
                   "$id": "#/properties/general/properties/chartOptions/properties/animation/properties/duration",
                   "type": "integer",
                   "title": "The Duration Schema",
                   "default": 0,
                   "examples": [
                     0
                   ]
                 }
               }
             },
             "responsive": {
               "$id": "#/properties/general/properties/chartOptions/properties/responsive",
               "type": "boolean",
               "title": "The Responsive Schema",
               "default": false,
               "examples": [
                 true
               ]
             },
             "legend": {
               "$id": "#/properties/general/properties/chartOptions/properties/legend",
               "type": "object",
               "title": "The Legend Schema",
               "required": [
                 "labels",
                 "display"
               ],
               "properties": {
                 "labels": {
                   "$id": "#/properties/general/properties/chartOptions/properties/legend/properties/labels",
                   "type": "object",
                   "title": "The Labels Schema",
                   "required": [
                     "fontColor"
                   ],
                   "properties": {
                     "fontColor": {
                       "$id": "#/properties/general/properties/chartOptions/properties/legend/properties/labels/properties/fontColor",
                       "type": "string",
                       "title": "The Fontcolor Schema",
                       "default": "",
                       "examples": [
                         "#000080"
                       ],
                       "pattern": "^(.*)$"
                     }
                   }
                 },
                 "display": {
                   "$id": "#/properties/general/properties/chartOptions/properties/legend/properties/display",
                   "type": "boolean",
                   "title": "The Display Schema",
                   "default": false,
                   "examples": [
                     true
                   ]
                 }
               }
             },
             "scales": {
               "$id": "#/properties/general/properties/chartOptions/properties/scales",
               "type": "object",
               "title": "The Scales Schema",
               "required": [
                 "xAxes",
                 "yAxes"
               ],
               "properties": {
                 "xAxes": {
                   "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes",
                   "type": "array",
                   "title": "The Xaxes Schema",
                   "items": {
                     "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items",
                     "type": "object",
                     "title": "The Items Schema",
                     "required": [
                       "gridLines",
                       "ticks"
                     ],
                     "properties": {
                       "gridLines": {
                         "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items/properties/gridLines",
                         "type": "object",
                         "title": "The Gridlines Schema",
                         "required": [
                           "display"
                         ],
                         "properties": {
                           "display": {
                             "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items/properties/gridLines/properties/display",
                             "type": "boolean",
                             "title": "The Display Schema",
                             "default": false,
                             "examples": [
                               false
                             ]
                           }
                         }
                       },
                       "ticks": {
                         "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items/properties/ticks",
                         "type": "object",
                         "title": "The Ticks Schema",
                         "required": [
                           "fontStyle",
                           "fontColor",
                           "padding"
                         ],
                         "properties": {
                           "fontStyle": {
                             "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items/properties/ticks/properties/fontStyle",
                             "type": "string",
                             "title": "The Fontstyle Schema",
                             "default": "",
                             "examples": [
                               "bold"
                             ],
                             "pattern": "^(.*)$"
                           },
                           "fontColor": {
                             "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items/properties/ticks/properties/fontColor",
                             "type": "string",
                             "title": "The Fontcolor Schema",
                             "default": "",
                             "examples": [
                               "rgba(0,0,0,0.6)"
                             ],
                             "pattern": "^(.*)$"
                           },
                           "padding": {
                             "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/xAxes/items/properties/ticks/properties/padding",
                             "type": "integer",
                             "title": "The Padding Schema",
                             "default": 0,
                             "examples": [
                               0
                             ]
                           }
                         }
                       }
                     }
                   }
                 },
                 "yAxes": {
                   "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/yAxes",
                   "type": "array",
                   "title": "The Yaxes Schema",
                   "items": {
                     "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/yAxes/items",
                     "type": "object",
                     "title": "The Items Schema",
                     "required": [
                       "id",
                       "type",
                       "position"
                     ],
                     "properties": {
                       "id": {
                         "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/yAxes/items/properties/id",
                         "type": "string",
                         "title": "The Id Schema",
                         "default": "",
                         "examples": [
                           "Left"
                         ],
                         "pattern": "^(.*)$"
                       },
                       "type": {
                         "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/yAxes/items/properties/type",
                         "type": "string",
                         "title": "The Type Schema",
                         "default": "",
                         "examples": [
                           "linear"
                         ],
                         "pattern": "^(.*)$"
                       },
                       "position": {
                         "$id": "#/properties/general/properties/chartOptions/properties/scales/properties/yAxes/items/properties/position",
                         "type": "string",
                         "title": "The Position Schema",
                         "default": "",
                         "examples": [
                           "left"
                         ],
                         "pattern": "^(.*)$"
                       }
                     }
                   }
                 }
               }
             }
           }
         },
         "timerInterval": {
           "$id": "#/properties/general/properties/timerInterval",
           "type": "integer",
           "title": "The Timerinterval Schema",
           "default": 0,
           "examples": [
             500
           ]
         }
       }
     },
     "deployment": {
       "$id": "#/properties/deployment",
       "type": "object",
       "title": "The Deployment Schema",
       "required": [
         "apiLink",
         "apiPort",
         "protocol",
         "host"
       ],
       "properties": {
         "apiLink": {
           "$id": "#/properties/deployment/properties/apiLink",
           "type": "string",
           "title": "The Apilink Schema",
           "default": "",
           "examples": [
             "/api"
           ],
           "pattern": "^(.*)$"
         },
         "apiPort": {
           "$id": "#/properties/deployment/properties/apiPort",
           "type": "string",
           "title": "The Apiport Schema",
           "default": "",
           "examples": [
             "8080"
           ],
           "pattern": "^(.*)$"
         },
         "protocol": {
           "$id": "#/properties/deployment/properties/protocol",
           "type": "string",
           "title": "The Protocol Schema",
           "default": "",
           "examples": [
             "http"
           ],
           "pattern": "^(.*)$"
         },
         "host": {
           "$id": "#/properties/deployment/properties/host",
           "type": "string",
           "title": "The Host Schema",
           "default": "",
           "examples": [
             "localhost"
           ],
           "pattern": "^(.*)$"
         }
       }
     }
   }
 }

   /**
   * The editor used to edit the json file.
   */
  @ViewChild(JsonEditorComponent) editor: JsonEditorComponent;

  /**
  *
  */
  public options = new JsonEditorOptions();
  /**
  * Stores the data which is displayed and edited in the json editor
  */
  public data: IAppConfig;


  constructor(public appConfig: AppConfig) {
    // remove private values
    AppConfig.clear();
    this.data =  AppConfig.settings;
    this.options.mode = 'code';
    this.options.modes = ['code', 'text', 'tree', 'view'];
    //this.options.schema = this.schema;
    this.options.statusBar = false;
  }

  /**
  * Converts the content of the editor into a json object and sends it to the backend to store.
  */
  public onSavePressed() {
    AppConfig.settings = JSON.parse(this.editor.getText());
    this.appConfig.storeSettings();
  }

  ngAfterViewInit(): void {
      // fix. editor has problems with height.
      this.editor.jsonEditorContainer.nativeElement.style.height = "85vh";
  }
}
